USE master;
ALTER DATABASE [eventEase1.2] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
RESTORE DATABASE [eventEase1.2]
FROM DISK = N'C:\backups\eventEase1.2.bak'
WITH REPLACE;
ALTER DATABASE [eventEase1.2] SET MULTI_USER;
